apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .NAME }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .CLASS }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ .SERVICE }}
            port:
              number: {{ .PORT }}
